version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - category-service
      - player-service
      - question-service
      - tarrah-service
      - frontend
    networks:
      - backend

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - backend

  category-service:
    build:
      context: .
      dockerfile: category-service/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    networks:
      - backend

  player-service:
    build:
      context: .
      dockerfile: player-service/Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    networks:
      - backend

  question-service:
    build:
      context: .
      dockerfile: question-service/Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - mongo
    networks:
      - backend

  tarrah-service:
    build:
      context: .
      dockerfile: tarrah-service/Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - mongo
    networks:
      - backend

  frontend:
    build:
      context: ./WebProject_Phase2_Front_Group10
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - category-service
      - player-service
      - question-service
      - tarrah-service
    networks:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
