version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - category-service
      - player-service
      - question-service
      - tarrah-service
      - frontend
    networks:
      - backend

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydatabase
    networks:
      - backend

  category-service:
    build:
      context: .
      dockerfile: category-service/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydatabase
    networks:
      - backend

  player-service:
    build:
      context: .
      dockerfile: player-service/Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydatabase
    networks:
      - backend

  question-service:
    build:
      context: .
      dockerfile: question-service/Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydatabase
    networks:
      - backend

  tarrah-service:
    build:
      context: .
      dockerfile: tarrah-service/Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydatabase
    networks:
      - backend

  frontend:
    build:
      context: ./WebProject_Phase2_Front_Group10
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - category-service
      - player-service
      - question-service
      - tarrah-service
    networks:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  backend:
    driver: bridge

